pipeline {
  agent {
    node {
      label 'python'
    }
  }
    parameters {
        string(name:'MANUAL_DEPLOY',defaultValue: 'no',description:'yes or no')
      
        string(
            name:'REGISTRY',
            defaultValue: 'harbor.tkeel.io:30003',
            description:'REGISTRY')

        string(
            name:'REPOSITORY',
            defaultValue: 'tkeel-io',
            description:'REPOSITORY')

        string(
            name:'DOCKER_IMAGE_TAG',
            defaultValue: '2.0.0',
            description:'docker image tag')

        string(
            name:'HELM_CHART_VERSION',
            defaultValue: '2.0.0',
            description:'plugin version')

    }

    environment {
        /*
        tips:app env
        */
        APP_NAME = 'core'
        CHART_PATH = 'charts/core'
        DOCKERFILES_PATH = 'Dockerfile'
        
        /*
        CREDENTIAL
        */
        PRIVATE_REPO_CREDENTIAL_ID = 'harbor'
        KUBECONFIG_CREDENTIAL_ID = 'kubeconfig'

        /*
        config form CREDENTIAL
        */
        PRIVATE_REPO_CONFIG = 'private-repo'
        PLUGIN_CONFIG = 'tkeel-plugin-config'
    }

    stages {
        stage ('checkout scm') {
            steps {
                checkout(scm)
            }
        }

        stage('get config'){
            /*
            get form CREDENTIAL
            */
            steps {
                container ('python'){
                    withCredentials([usernamePassword(credentialsId: "$PRIVATE_REPO_CONFIG", usernameVariable: 'registry',passwordVariable: 'repository')]) {
                        script {
                            env.REGISTRY = registry
                            env.REPOSITORY = repository
                            }
                        }

                    withCredentials([usernamePassword(credentialsId: "$PRIVATE_REPO_CREDENTIAL_ID", usernameVariable: 'username',passwordVariable: 'password')]) {
                        script {
                            env.USERNAME = username
                            env.PASSWORD = password
                            }
                        }

                    withCredentials([usernamePassword(credentialsId: "$PLUGIN_CONFIG", usernameVariable: 'enable_config',passwordVariable: 'config')]) {
                        script {
                            env.TKEEL_PLUGIN_ENABLE_UPGRADE = enable_config
                            env.TKEEL_PLUGIN_CONFIG = config
                            }
                        }
                    }
                }
            }

        stage('set env'){
            environment {
                COMMIT_ID = "${sh(script:'git rev-parse --short HEAD',returnStdout:true)}"
                TIMESTAMP = "${sh(script:'date -d "+8 hour" "+%m.%d.%H%M%S"',returnStdout:true)}"
            }
            steps {
                container ('python'){
                    script {
                        if (params.MANUAL_DEPLOY == "yes"){
                            /*
                            overwrite REGISTRY & REPOSITORY
                            */
                            env.REGISTRY = params.REGISTRY
                            env.REPOSITORY = params.REPOSITORY

                            /*
                            new Docker tag & chart version
                            */
                            env.DOCKER_IMAGE_TAG = params.DOCKER_IMAGE_TAG
                            env.DOCKER = "${env.REGISTRY}/${env.REPOSITORY}/${env.APP_NAME}:${env.DOCKER_IMAGE_TAG}"
                            env.CHART = params.HELM_CHART_VERSION

                        }else{
                            /*
                            Docker tag & chart version
                            */
                            env.DOCKER_IMAGE_TAG = env.COMMIT_ID
                            env.DOCKER = "${env.REGISTRY}/${env.REPOSITORY}/${env.APP_NAME}:${env.DOCKER_IMAGE_TAG}"
                            env.CHART = "${env.TIMESTAMP.trim()}-${env.BRANCH_NAME}"
                        }
                    }
                }
            }
        }

        stage('build & push') {
            environment {
                /*
                helm env
                */
                HELM_EXPERIMENTAL_OCI=1
            }
            steps {
                container ('python') {
                    script{
                        /*
                        edit chart
                        */
                        env.new_repository = "${env.REGISTRY}/${env.REPOSITORY}/${env.APP_NAME}"
                        sh 'python3 devops/scripts/kotb.py write $CHART_PATH/values.yaml $CHART_PATH/values.yaml $new_repository'

                        /*
                        package helm chart
                        */
                        sh 'helm3 registry login -u $USERNAME -p $PASSWORD $REGISTRY'
                        sh 'helm3 package $CHART_PATH --version=$CHART --app-version=$DOCKER_IMAGE_TAG' 
                        sh 'helm3 cm-push $APP_NAME-*.tgz https://$REGISTRY/chartrepo/$REPOSITORY --username=$USERNAME --password=$PASSWORD'

                        /*
                        build docker image
                        */
                        sh 'docker login -u $USERNAME -p $PASSWORD https://$REGISTRY'
                        sh 'docker build -f $DOCKERFILES_PATH -t $DOCKER .'
                        sh 'docker push $DOCKER'
                    }
                }
            }
        }
 
        stage('install or upgrade plugin') {
            steps {
                container ('python') {
                    withCredentials([kubeconfigFile(credentialsId: env.KUBECONFIG_CREDENTIAL_ID,variable: 'KUBECONFIG')]) {
                        script {                        
                            if (env.TKEEL_PLUGIN_ENABLE_UPGRADE == 'yes'){
                                sh 'tkeel admin login -p changeme'
                                sh 'mv devops/config/$TKEEL_PLUGIN_CONFIG ~/.tkeel/config.yaml'
                                sh 'tkeel upgrade --repo-url=https://$REGISTRY/chartrepo/$REPOSITORY --repo-name=$REPOSITORY  --core-version=$CHART'
                            }else{
                                sh 'echo do not install or upgrade'
                            }
                        }
                    }                
                }
            }
        }
    }
}
