name: Proposal
description: File a feature request
title: "[proposal]: "
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your key comments
  - type: textarea
    id: what-except
    attributes:
      label: What Is Your Expect
      description: We would love to know what you need
      placeholder: Tell us what you want!
      value: "Maybe ..."
    validations:
      required: true