apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: core-state
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: redisType
      value: node
    - name: redisDB
      value: 5
